//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandWindCMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public string RealName { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public bool Enable { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Sex { get; set; }
        public string QQ { get; set; }
        public string PhoneNumber { get; set; }
        public string Telephone { get; set; }
        public string EMail { get; set; }
        public string Code { get; set; }
        public Nullable<bool> IsDevelpoer { get; set; }
        public string OpenId { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
